# Generated by Django 2.2 on 2019-05-01 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_number', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('meetings_schedule', models.CharField(max_length=50)),
                ('meeting_day', models.CharField(max_length=15)),
                ('created_date', models.DateTimeField(verbose_name='Date Created')),
                ('updated_date', models.DateTimeField(verbose_name='Date Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(verbose_name='Date Created')),
                ('updated_date', models.DateTimeField(verbose_name='Date Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateTimeField(verbose_name='Meeting Date')),
                ('created_date', models.DateTimeField(verbose_name='Date Created')),
                ('updated_date', models.DateTimeField(verbose_name='Date Updated')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarttm_web.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_membership_date', models.DateTimeField(verbose_name='Date Joined')),
                ('created_date', models.DateTimeField(verbose_name='Date Created')),
                ('updated_date', models.DateTimeField(verbose_name='Date Updated')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarttm_web.Club')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=200)),
                ('secondary_email', models.CharField(max_length=200)),
                ('mobile_phone', models.CharField(max_length=200)),
                ('home_phone', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=10)),
                ('membership_date', models.DateTimeField(verbose_name='Date Joined')),
                ('toastmaster_id', models.IntegerField(default=0)),
                ('paid_until', models.DateTimeField(verbose_name='Expiry Date')),
                ('created_date', models.DateTimeField(verbose_name='Date Created')),
                ('updated_date', models.DateTimeField(verbose_name='Date Updated')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created_by', to='smarttm_web.User')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_by', to='smarttm_web.User')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('seniority', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(verbose_name='Date Created')),
                ('updated_date', models.DateTimeField(verbose_name='Date Updated')),
                ('status', models.CharField(max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_created_by', to='smarttm_web.User')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_updated_by', to='smarttm_web.User')),
            ],
        ),
        migrations.CreateModel(
            name='Participation_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(verbose_name='Date Created')),
                ('updated_date', models.DateTimeField(verbose_name='Date Updated')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participationtype_created_by', to='smarttm_web.User')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participationtype_updated_by', to='smarttm_web.User')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_seconds', models.IntegerField(default=0)),
                ('ah_count', models.IntegerField(default=0)),
                ('vote_count', models.IntegerField(default=0)),
                ('grammar_good', models.CharField(max_length=200)),
                ('grammar_bad', models.CharField(max_length=200)),
                ('grammar_remarks', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(verbose_name='Date Created')),
                ('updated_date', models.DateTimeField(verbose_name='Date Updated')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_created_by', to='smarttm_web.User')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_evaluation', to='smarttm_web.Evaluation')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarttm_web.Meeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarttm_web.Member')),
                ('participation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarttm_web.Participation_Type')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_updated_by', to='smarttm_web.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_responsible', to='smarttm_web.User')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_created_by', to='smarttm_web.User'),
        ),
        migrations.AddField(
            model_name='member',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_updated_by', to='smarttm_web.User'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to='smarttm_web.User'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_created_by', to='smarttm_web.User'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_updated_by', to='smarttm_web.User'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_created_by', to='smarttm_web.User'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_participation', to='smarttm_web.Participation'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_updated_by', to='smarttm_web.User'),
        ),
        migrations.CreateModel(
            name='EC_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(verbose_name='Date Created')),
                ('updated_date', models.DateTimeField(verbose_name='Date Updated')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarttm_web.Club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecmember_created_by', to='smarttm_web.User')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarttm_web.Member')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarttm_web.Position')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecmember_updated_by', to='smarttm_web.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_responsible', to='smarttm_web.User')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_created_by', to='smarttm_web.User'),
        ),
        migrations.AddField(
            model_name='club',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_updated_by', to='smarttm_web.User'),
        ),
    ]
