# Generated by Django 2.2 on 2019-05-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttm_web', '0002_auto_20190501_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='club',
            name='meeting_day',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='meetings_schedule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Updated'),
        ),
    ]
