# Generated by Django 2.2 on 2019-05-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttm_web', '0012_auto_20190502_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
