# Generated by Django 2.2 on 2019-05-05 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarttm_web', '0019_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_EC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarttm_web.Position'),
        ),
    ]
