# Generated by Django 2.2.1 on 2019-05-08 09:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('smarttm_web', '0022_auto_20190507_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 8, 9, 29, 34, 170673, tzinfo=utc), verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 8, 9, 29, 34, 170673, tzinfo=utc), verbose_name='Date Updated'),
        ),
    ]
