# Generated by Django 2.2.1 on 2019-05-08 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smarttm_web', '0023_auto_20190508_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date Updated'),
        ),
    ]
