# Generated by Django 2.2.1 on 2019-09-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttm_web', '0032_auto_20190630_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='summary_sent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Summary Sent Date'),
        ),
        migrations.AddField(
            model_name='summary',
            name='part_percent',
            field=models.IntegerField(default=0),
        ),
    ]
