# Generated by Django 2.2.4 on 2019-11-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttm_web', '0033_auto_20190901_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
