# Generated by Django 2.2.13 on 2020-07-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttm_web', '0034_summary_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('prep_speech_count', models.IntegerField(default=0)),
                ('tt_speech_count', models.IntegerField(default=0)),
                ('eval_speech_count', models.IntegerField(default=0)),
                ('adv_roles_count', models.IntegerField(default=0)),
                ('present_count', models.IntegerField(default=0)),
                ('parts_count', models.IntegerField(default=0)),
                ('meeting_part_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='summary',
            name='ge_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='toe_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='ttm_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
