# Generated by Django 2.2.13 on 2020-07-08 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarttm_web', '0035_auto_20200703_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.BooleanField(default=False)),
                ('requested_date', models.DateField(verbose_name='Requested Date')),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name='Date Created')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Date Updated')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarttm_web.Club')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_created_by', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarttm_web.Member')),
                ('participation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarttm_web.Participation_Type')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
