# Generated by Django 2.2 on 2019-05-02 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarttm_web', '0010_auto_20190502_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarttm_web.Member'),
        ),
    ]
