# Generated by Django 2.2.1 on 2019-05-07 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarttm_web', '0020_auto_20190505_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='user',
        ),
    ]
