# Generated by Django 2.2.1 on 2019-05-07 08:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('smarttm_web', '0021_remove_participation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='club_membership_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 7, 8, 14, 57, 602267, tzinfo=utc), verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 7, 8, 14, 57, 602267, tzinfo=utc), verbose_name='Date Updated'),
        ),
    ]
