# Generated by Django 2.2.1 on 2019-05-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttm_web', '0024_auto_20190508_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting_Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(blank=True, null=True, verbose_name='Meeting Date')),
                ('speech_count', models.IntegerField(default=0)),
                ('tt_count', models.IntegerField(default=0)),
                ('prep_speech_count', models.IntegerField(default=0)),
            ],
        ),
    ]
