# Generated by Django 2.2.1 on 2019-06-27 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarttm_web', '0027_auto_20190516_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='smarttm_web.Club'),
        ),
    ]
