# Generated by Django 2.2.1 on 2019-06-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarttm_web', '0028_auto_20190627_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='status',
            new_name='paid_status',
        ),
    ]
