# Generated by Django 2.2.1 on 2019-06-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttm_web', '0030_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_no',
            field=models.CharField(default='x1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting_summary',
            name='members_absent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting_summary',
            name='members_present_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='attendance_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='last_two_meetings_att',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='tt_percent',
            field=models.IntegerField(default=0),
        ),
    ]
