# Generated by Django 2.2 on 2019-05-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarttm_web', '0003_auto_20190501_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation_type',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='ec_member',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecmember_created_by', to='smarttm_web.User'),
        ),
        migrations.AlterField(
            model_name='ec_member',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='ec_member',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecmember_updated_by', to='smarttm_web.User'),
        ),
        migrations.AlterField(
            model_name='ec_member',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_created_by', to='smarttm_web.User'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_updated_by', to='smarttm_web.User'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_created_by', to='smarttm_web.User'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_updated_by', to='smarttm_web.User'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='member',
            name='club_membership_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='member',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_created_by', to='smarttm_web.User'),
        ),
        migrations.AlterField(
            model_name='member',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_updated_by', to='smarttm_web.User'),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participation_created_by', to='smarttm_web.User'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_evaluation', to='smarttm_web.Evaluation'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='grammar_bad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='grammar_good',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='grammar_remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participation_updated_by', to='smarttm_web.User'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='participation_type',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participationtype_created_by', to='smarttm_web.User'),
        ),
        migrations.AlterField(
            model_name='participation_type',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='participation_type',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participationtype_updated_by', to='smarttm_web.User'),
        ),
        migrations.AlterField(
            model_name='participation_type',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='position',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_created_by', to='smarttm_web.User'),
        ),
        migrations.AlterField(
            model_name='position',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='position',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_updated_by', to='smarttm_web.User'),
        ),
        migrations.AlterField(
            model_name='position',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Updated'),
        ),
    ]
